{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1092318a_4bd4bc03",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000994
      },
      "writtenOn": "2022-07-29T07:19:11Z",
      "side": 1,
      "message": "Looks very nice!\nPlease check one inline suggestion, otherwise I suppose it\u0027s great.",
      "revId": "5d66b22e740a7f998fe670ab5603607894d17411",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "582a9e59_288dcc4a",
        "filename": "sfx2/source/doc/objstor.cxx",
        "patchSetId": 3
      },
      "lineNbr": 2629,
      "author": {
        "id": 1000994
      },
      "writtenOn": "2022-07-29T07:19:11Z",
      "side": 1,
      "message": "In this place, the ERRCODE_ABORT is not necessarily from pMediumTmp. This \u0027else\u0027 branch happens either when SaveTo_Impl failed, *or* when GetError() already returned some error.\n\nI suggest to store the result of pMediumTmp-\u003eGetError() to a variable, then use it in SetError, and then check *its* value here, to be sure we obtain it from the medium, not from elsewhere (no idea if ERRCODE_ABORT is possible in other places, but it\u0027s better to be explicit and precise, right?).",
      "revId": "5d66b22e740a7f998fe670ab5603607894d17411",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "17d1503c_fdd79587",
        "filename": "sfx2/source/doc/objstor.cxx",
        "patchSetId": 3
      },
      "lineNbr": 2629,
      "author": {
        "id": 1003042
      },
      "writtenOn": "2022-07-29T18:13:11Z",
      "side": 1,
      "message": "Actually the ERRCODE_ABORT is from pMediumTmp because line 2627 sets the error code from pMediumTmp which is then read on line 2629.  I changed it anyway though to help with readability.",
      "parentUuid": "582a9e59_288dcc4a",
      "revId": "5d66b22e740a7f998fe670ab5603607894d17411",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6073f603_d32e5fec",
        "filename": "sfx2/source/doc/objstor.cxx",
        "patchSetId": 3
      },
      "lineNbr": 2629,
      "author": {
        "id": 1000994
      },
      "writtenOn": "2022-07-29T20:52:27Z",
      "side": 1,
      "message": "\u003e Actually the ERRCODE_ABORT is from pMediumTmp because line 2627 sets the error code from pMediumTmp which is then read on line 2629.\n\nActually no. Before writing my comment, I read the code of SetError:\n\n  void SfxObjectShell::SetError(ErrCode lErr)\n  {\n      if (pImpl-\u003elErr\u003d\u003dERRCODE_NONE)\n      {\n          pImpl-\u003elErr\u003dlErr;\n      }\n  }\n\nSo again: the ERRCODE_ABORT may come from elsewhere, if it was there before the call to SetError in line 2627.\n\nThanks for changing it!",
      "parentUuid": "17d1503c_fdd79587",
      "revId": "5d66b22e740a7f998fe670ab5603607894d17411",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8021e9cf_50b58f8a",
        "filename": "sfx2/source/doc/objstor.cxx",
        "patchSetId": 3
      },
      "lineNbr": 2629,
      "author": {
        "id": 1003042
      },
      "writtenOn": "2022-07-29T23:07:35Z",
      "side": 1,
      "message": "Yes, I see now that the ABORT could have been set before.  It seems also that there could have been a different error stored when abort is trying to be set here, which would have skipped the new if check and avoided the return.  Good call.",
      "parentUuid": "6073f603_d32e5fec",
      "revId": "5d66b22e740a7f998fe670ab5603607894d17411",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    }
  ]
}