{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "48ea6c75_d453f06a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1000179
      },
      "writtenOn": "2022-02-01T16:43:23Z",
      "side": 1,
      "message": "This is a UItest, the windows failure is not related, in fact is not even run there. pushing",
      "revId": "61eaaa901b7a3ee117ef3f287de8e8740bd775e4",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    }
  ]
}